name: Build Site
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Hugo Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Setup SSH
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        run: |
          echo "$DEPLOY_KEY" > deploy_key
          chmod 600 ./deploy_key
      - name: Test SSH
        run: ssh -i ./deploy_key -o StrictHostKeyChecking=no ${{secrets.DEPLOY_USER}}@${{secrets.DEPLOY_HOST}}
      - name: Deploy
        env:
          DEST: ${{secrets.DEPLOY_USER}}@${{secrets.DEPLOY_HOST}}:${{secrets.DEPLOY_DIRECTORY}}
        run: rsync -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' -r --quiet public/* $DEST
